### ISSUE TITLE
Cachelib build result contains many absolute path

### ISSUE THREAD

**Issue by GavinMar** [facebook/CacheLib#162] opened 2022-09-22 03:20 UTC
The Cachelib build output contains many local absolute file path, especially in pkgconfig and cmake files. If we want to copy the output to another machine, we need to put them to the same path, or may not found some dependency when we building. It seems so inflexible.

So, how can we solve this problem if we want our build output library can be used by different user and different hosts?

**Comment by jaesoo-fb** [comment] 2022-09-22 18:48
(CC @agordon)

**Comment by jaesoo-fb** [comment] 2022-11-30 18:57
Duplicate of #173

**Closed by jaesoo-fb** 2022-11-30 18:57 UTC
