### ISSUE TITLE
ItemHandle from find() is nullptr from NVMCache after large concurrent writes

### ISSUE THREAD

**Issue by wenhaocs** [facebook/CacheLib#150] opened 2022-06-30 19:04 UTC
**Describe the bug**
I am implementing a cache using hybrid cache feature of CacheLib. When I am doing a test of directly inserting large amount of data into NVMCache (I wait explicitly `handle.wait()`), and then read data out using `handle.find()`, a lot of returned handle which `wentToNVM` but now points to `nullptr`. 

In details, here is my list of cache config.
```
config
          .setCacheSize(40 * 1024 * 1024)
          .setCacheName(name_)
          .setAccessConfig(std::pow(2, cacheEntriesPower_));
  nvmConfig.navyConfig.setSimpleFile(<some path>,100 * 1024 * 1024,false);
  nvmConfig.navyConfig.setBlockSize(4096);
  nvmConfig.navyConfig.blockCache().setRegionSize(16 * 1024 * 1024);
  config.enableNvmCache(nvmConfig);
```

I add a small DRAM pool:
`cacheInternal_->addPool(poolName, 10 * 1024 * 1024);`

Here is my test:
```
for (auto i = 0; i < 10240; i++) {
    std::string key = std::to_string(i);
    std::string val = longText + key;     // longText is 4KB size
    // put vertex
    auto status = cache->Insert(key, val);
    EXPECT_TRUE(status.ok());
  }

for (auto i = 0; i <= 10240; i++) {
    std::string key = std::to_string(i);
    auto handle = cache->lookup(key);   // This function will wrap find() and wait();
    EXPECT_NE(handle, nullptr);
   ..........
  }
```
Note here I am using a fixed file name as navy device file.
In this test, the small keys (starting from 0) will be evicted to NVM. When I run this test for the first time, around the first 1300 handles are not nullptr, but the remaining handles from NVM are nullptr. If I run a second time, more handles (around 3000) are not nullptr. If I continue this and about run 4 times, all returned handles do not equal to nullptr and can retrieve data.
In terms of the navy file size, the first run of the test will fail and the file size is 16MB. The second run will fail, but the file size increased to 32MB. This process continued. After the last successful run, the file size is 81MB.

So I guess, maybe it is because the device file increase speed doesn't match the speed of evicting to NVM. What if I `dd` a file in advance? If I `dd` a 100MB file as the navy device file in advance. The aforementioned test can pass. 

Another interesting thing is if I increase the DRAM part cache size by changing the pool size from 10MB to 30MB, the test can pass too. With this in mind, I tried to reproduce the error with your `ConcurrentFills` in `cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp`

**To Reproduce**
Here are the changes I made:

```
diff --git a/cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp b/cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp
index 28051e7f..944ec266 100644
--- a/cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp
+++ b/cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp
@@ -357,11 +357,11 @@ TEST_F(NvmCacheTest, ConcurrentFills) {
   auto& nvm = this->cache();
   auto pid = this->poolId();

-  const int nKeys = 1024;
+  const int nKeys = 10240;

   for (unsigned int i = 0; i < nKeys; i++) {
     auto key = std::string("blah") + folly::to<std::string>(i);
-    auto it = nvm.allocate(pid, key, 15 * 1024);
+    auto it = nvm.allocate(pid, key, 4 * 1024);
     ASSERT_NE(nullptr, it);
     *((int*)it->getMemory()) = i;
     nvm.insertOrReplace(it);
@@ -370,7 +370,7 @@ TEST_F(NvmCacheTest, ConcurrentFills) {
   auto doConcurrentFetch = [&](int id) {
     auto key = std::string("blah") + folly::to<std::string>(id);
     std::vector<std::thread> thr;
-    for (unsigned int j = 0; j < 50; j++) {
+    for (unsigned int j = 0; j < 1; j++) {
       thr.push_back(std::thread([&]() {
         auto hdl = nvm.find(key);
         hdl.wait();
@@ -378,12 +378,12 @@ TEST_F(NvmCacheTest, ConcurrentFills) {
         ASSERT_EQ(id, *(int*)hdl->getMemory());
       }));
     }
-    for (unsigned int j = 0; j < 50; j++) {
+    for (unsigned int j = 0; j < 1; j++) {
       thr[j].join();
     }
   };

-  for (unsigned int i = 0; i < 10; i++) {
+  for (unsigned int i = 0; i < 10240; i++) {
     doConcurrentFetch(i);
   }
 }

diff --git a/cachelib/allocator/tests/NvmTestUtils.h b/cachelib/allocator/tests/NvmTestUtils.h
index 8f53d24b..2f1c8974 100644
--- a/cachelib/allocator/tests/NvmTestUtils.h
+++ b/cachelib/allocator/tests/NvmTestUtils.h
@@ -31,7 +31,7 @@ inline NavyConfig getNvmTestConfig(const std::string& cacheDir) {
   config.setDeviceMetadataSize(4 * 1024 * 1024);
   config.setBlockSize(1024);
   config.setNavyReqOrderingShards(10);
-  config.blockCache().setRegionSize(4 * 1024 * 1024);
+  config.blockCache().setRegionSize(16 * 1024 * 1024);
   config.bigHash()
       .setSizePctAndMaxItemSize(50, 100)
       .setBucketSize(1024)
```

And you will see the error:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/19355821/176757504-e0e457a9-5cd1-4d3b-b880-ac906ce923cd.png">

**System:**
 - OS: Ubuntu20.04
 - Disk: NVMe SSD

**Additional context**
Can you help let me know if this is a potential bug or the configuration issue? Thanks!

**Comment by haowu14** [comment] 2022-07-05 21:14
Hi @wenhaocs , can you print out the number of nvm evictions via cache.getGlobalCacheStats().numNvmEvictions in your setup?

**Comment by wenhaocs** [comment] 2022-07-05 22:18
If I set the navy file size to be 100MB (all block), it's always 0 as no nvm eviction happens. If I set navy file size to be 50MB (all block), the `numNvmEvictions` is 1824, 1732, 1733, 1731 when the first `nullptr` itemHandle is returned. BTW, in this case, the test will not pass any more  with 30MB DRAM.

**Comment by haowu14** [comment] 2022-07-05 22:22
Let me explain this behavior in the unit test setup. Then you can see whether it is desirable and actually reflects the problem you experienced.

In the unit test setup you shared, the region size is set to 16MB. The overall size designated to BlockCache is about 46MB (100MB - 50MB big hash - 4MB metadata). So in the end, block cache 2 regions totaling at 32MB.
Also, by default we have 1 clean region, meaning that if there is less than 1 regions being clean, block cache will evict one region. Under such setup, as soon as we start writing into the second region, the first region gets reclaimed and the items are evicted.
In addition, the setup in the unit test has an allocation size of 20KB (see cachelib/allocator/nvmcache/tests/NvmTestBase.h poolAllocsizes_) and without truncating (enableNvmCacheTruncateAllocSize() in cachelib/allocator/CacheAllocatorConfig.h), each item takes 20KB in the region. So each region holds about 16MB/20KB ~ 819 items.

So under this setup, evictions are bound to happen.

**Comment by wenhaocs** [comment] 2022-07-05 22:31
I see. I redo the unit test. I print out the number of evictions when the returned itemHandle is nullptr. Here is the result:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/19355821/177427757-c3840ad8-a769-468c-b055-329115294a58.png">

They are 799, 1598,  1601, 1604, 1607, 1611 and continues growing...

**Comment by haowu14** [comment] 2022-07-05 22:47
The behavior in the unit test is expected. We only hold about 800 items in NVM while we insert and lookup 10240 items. So evictions will happen for sure. 

I want to know more about your actual setup. A few questions:
- Are you using shareMemNew to create this cache?
- Other than the code you shared, do you change other setups?
- Once you do `auto it = cache.allocate()` can you print `cache.getUsableSize(*it)`? This lets us know the actual size the item is taking. We may assume all the items takes the same size.
And at the end of tests, can you please print out `cache.getNvmCacheStatsMap().find("navy_bc_num_clean_regions")->second`?

**Comment by wenhaocs** [comment] 2022-07-05 23:36
(1) No `shareMemNew`
(2) The setup is exactly the same as I posted. `(100MB block navy, 10 DRAM pool, 16MB region size)`
(3) the actual size of the items are 4507, 4508, 4509, 4510, 4511
(4) the navy_bc_num_clean_regions is `1` when the first nullptr itemHandle is returned. 

Note that the UnitTest will fail too with the config I posted in the patch.

**Comment by haowu14** [comment] 2022-07-06 02:45
Making sure I have no confusions, are you using `Cache cache{config};` to create the cache and not shareMemAttach/New?

**Comment by wenhaocs** [comment] 2022-07-06 03:25
Correct. I am not using the persistence feature.

**Comment by haowu14** [comment] 2022-07-06 03:55
I was able to reproduce some of the behavior. 

For example, if we have RAM pool 10MB and NVM 50MB for block cache with 16MB region size. In block cache we have 3 regions (region 0, 1, 2). With 1 clean region, it means as soon as we start writing into region 2, all items in region 0 get evicted.
Let's ignore the nvm overheads and assume each item takes 4500 bytes. DRAM can hold 10MB/4500 ~ 2275 items. Each region in block cache holds 16MB/4500 ~ 3641 items. We run a loop to insert item 0 through item 10239. When we are inserting item 2275, item 0 gets evicted from DRAM and written into region 0. When inserting item (2275+3641 =) 5916, we start writing item 3641 into region 1. When inserting item (2275+3641*2=) 9557, we start writing item 7282 into region 2 and evicting region 0. Now item 0~3641 are out of the cache. When insertion of the last item 10239 is completed, we have DRAM [10239, 7964], region 1 [3641, 7281], region 2 [7282, 7963], region 0 clean. The numbers may not be accurate because in NVM, it takes more than 4500 bytes but this is the idea.

Now we start doing lookup from item 0 to 10239. We will get nullptr for 0 to 3640. When looking up 3641, the item is fetched from NVM into RAM, evicting item 7964 into region 2. We keep doing this until when looking up 5916, we kick 10239 into NVM. Now we have RAM [5916, 3641], region 1 [3641, 7281], region 2 [7282, 10239]. Then we will keep reading 5917, evicting 3641 but it doesn't get written into NVM because it is already there. When we reach the end of the loop, we have RAM [10239, 7964], region 1 [3641, 7281], region 2 [7282, 10239].

It's the same idea with 30MB ram but the NVM evictions start when looking up, the NVM items getting fetched into RAM.

What I can not reproduce is the behavior you described in the beginning, where your file size grows between runs.

**Comment by haowu14** [comment] 2022-07-06 04:27
To summarize, the behavior you observed that some of the `hdl == nullptr` is expected given the setup you provided. There are two slightly counterintuitive points:
1. We try to keep one clean region, meaning that we have N-1 regions in total. And in those N-1 regions, there could be 1 region that's just getting written into.
2. Aside from insert, lookup may also cause nvm eviction. This is because it an item is found in NVM, it is inserted into DRAM and that could cause an item to be evicted from DRAM and inserted into NVM, causing NVM eviction.
BTW `handle` pointing to nullptr with `wentToNvm` is expected. We mark all handles form nvm as `wentToNvm` regardless of whether it is a hit.

**Comment by wenhaocs** [comment] 2022-07-06 18:29
Thank you so much for explaining the eviction process. Now it's clear why the itemhandle is `nullptr` in the 50MB block cache case in the UnitTest. However, if I change the block cache into 100MB, there are still a lot of `nullptr` handle where in theory all items should be in NVM cache. I print out the key when the handle is nullptr from handle:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/19355821/177618422-9895676e-f90a-45c2-a325-82f2a19d796e.png">


For your convenience, here is the summary of git diff：
```
--- a/cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp
+++ b/cachelib/allocator/nvmcache/tests/NvmCacheTests.cpp
@@ -357,11 +357,13 @@ TEST_F(NvmCacheTest, ConcurrentFills) {
   auto& nvm = this->cache();
   auto pid = this->poolId();

-  const int nKeys = 1024;
+  const int nKeys = 10240;

   for (unsigned int i = 0; i < nKeys; i++) {
     auto key = std::string("blah") + folly::to<std::string>(i);
-    auto it = nvm.allocate(pid, key, 15 * 1024);
+    auto it = nvm.allocate(pid, key, 4 * 1024);
+    // std::cout << "allocation size: " << nvm.getUsableSize(*it);
+
     ASSERT_NE(nullptr, it);
     *((int*)it->getMemory()) = i;
     nvm.insertOrReplace(it);
@@ -370,20 +372,17 @@ TEST_F(NvmCacheTest, ConcurrentFills) {
   auto doConcurrentFetch = [&](int id) {
     auto key = std::string("blah") + folly::to<std::string>(id);
     std::vector<std::thread> thr;
-    for (unsigned int j = 0; j < 50; j++) {
-      thr.push_back(std::thread([&]() {
-        auto hdl = nvm.find(key);
-        hdl.wait();
-        ASSERT_NE(hdl, nullptr);
-        ASSERT_EQ(id, *(int*)hdl->getMemory());
-      }));
-    }
-    for (unsigned int j = 0; j < 50; j++) {
-      thr[j].join();
+    auto hdl = nvm.find(key);
+    hdl.wait();
+    if (!hdl) {
+        std::cout << "num evictions: " << nvm.getGlobalCacheStats().numNvmEvictions << std::endl;
+       std::cout << "id: " << id << std::endl;
     }
+    ASSERT_NE(hdl, nullptr);
+    ASSERT_EQ(id, *(int*)hdl->getMemory());
   };

-  for (unsigned int i = 0; i < 10; i++) {
+  for (unsigned int i = 0; i < 10240; i++) {
     doConcurrentFetch(i);
   }
 }

diff --git a/cachelib/allocator/nvmcache/tests/NvmTestBase.cpp b/cachelib/allocator/nvmcache/tests/NvmTestBase.cpp
index c76dcde6..64743c9c 100644
--- a/cachelib/allocator/nvmcache/tests/NvmTestBase.cpp
+++ b/cachelib/allocator/nvmcache/tests/NvmTestBase.cpp
@@ -49,7 +49,7 @@ NvmCacheTest::NvmCacheTest() {
 AllocatorT& NvmCacheTest::makeCache() {
   cache_.reset();
   cache_ = std::make_unique<LruAllocator>(allocConfig_);
-  id_ = cache_->addPool("default", poolSize_, poolAllocsizes_);
+  id_ = cache_->addPool("default", poolSize_);
   return *cache_;
 }

diff --git a/cachelib/allocator/nvmcache/tests/NvmTestBase.h b/cachelib/allocator/nvmcache/tests/NvmTestBase.h
index b0f94e41..82ef3a71 100644
--- a/cachelib/allocator/nvmcache/tests/NvmTestBase.h
+++ b/cachelib/allocator/nvmcache/tests/NvmTestBase.h
@@ -169,7 +169,7 @@ class NvmCacheTest : public testing::Test {
   // cache instance
   std::unique_ptr<AllocatorT> cache_;

-  size_t poolSize_{8 * 1024 * 1024};
+  size_t poolSize_{10 * 1024 * 1024};

diff --git a/cachelib/allocator/tests/NvmTestUtils.h b/cachelib/allocator/tests/NvmTestUtils.h
index 8f53d24b..4a771299 100644
--- a/cachelib/allocator/tests/NvmTestUtils.h
+++ b/cachelib/allocator/tests/NvmTestUtils.h
@@ -27,15 +27,15 @@ namespace utils {
 using NavyConfig = navy::NavyConfig;
 inline NavyConfig getNvmTestConfig(const std::string& cacheDir) {
   NavyConfig config{};
-  config.setSimpleFile(cacheDir + "/navy", 100 * 1024ULL * 1024ULL);
-  config.setDeviceMetadataSize(4 * 1024 * 1024);
-  config.setBlockSize(1024);
-  config.setNavyReqOrderingShards(10);
-  config.blockCache().setRegionSize(4 * 1024 * 1024);
-  config.bigHash()
-      .setSizePctAndMaxItemSize(50, 100)
-      .setBucketSize(1024)
-      .setBucketBfSize(8);
+  config.setSimpleFile("/tmp/navy", 100 * 1024ULL * 1024ULL);
+  // config.setDeviceMetadataSize(4 * 1024 * 1024);
+  config.setBlockSize(4096);
+  // config.setNavyReqOrderingShards(10);
+  config.blockCache().setRegionSize(16 * 1024 * 1024);
+  //config.bigHash()
+  //    .setSizePctAndMaxItemSize(50, 100)
+  //    .setBucketSize(1024)
+  //    .setBucketBfSize(8);
   return config;
 }
```

**Comment by haowu14** [comment] 2022-07-07 02:44
In this new setup, I was able to reproduce the problem sometimes. I believe it is due to another race condition.
Let's make sure we have the same race here:

When you finish inserting, please print out the following metrics: nvm.getGlobalCacheStats().numNvmPuts/numNvmAbortedPutOnTombstone/numNvmPutEncodeFailure/numNvmAbortedPutOnInflightGet and nvm.getNvmCacheStatsMap().find("navy_inserts").
You just need to print once right after all the inserts.

If you have numNvmAbortedPutOnTombstone > 0 and numNvmAbortedPutOnTombstone + "navy_inserts" = numNvmPuts, then we have the same condition.

When we do `insertOrReplace` in hybrid cache, we issue a nvm remove (https://github.com/facebook/CacheLib/blob/main/cachelib/allocator/CacheAllocator-inl.h#L1063). This remove will create and hold a tombstone until it is completed. The remove will be executed asynchronously. If when the item is being evicted from DRAM the remove request is still not picked up and the tombstone is still there, the nvm put is aborted (https://github.com/facebook/CacheLib/blob/main/cachelib/allocator/nvmcache/NvmCache-inl.h#L468). Therefore this item is not written into NVM.

The behavior that aborting put when a tombstone is present is intended. But it is true that our unit test is flaky here.

**Comment by wenhaocs** [comment] 2022-07-13 18:52
Yes, the stats printed out are the same. Now I am clear why the data inserted into NVM may not be available when reading out. On the other hand, how can we avoid the case that the NVM remove is still not completed when eviction from DRAM is issued? I guess:

(1) Reduce the number of DRAM eviction to Navy by allocating larger DRAM?
(2) Set `truncate` to true so file is preallocated and the speed of navy can be little faster?

I think in some cases the NVM cache miss matters due to the overhead. It's better to directly read data out from backend storage rather than get cache miss first and then read out from storage.

**Comment by haowu14** [comment] 2022-07-25 18:49
We committed a fix to the unit test NvmCacheTest.ConcurrentFills so that it won't fail due to the above race condition. Closing this issue.

**Closed by haowu14** 2022-07-25 18:49 UTC
